---
intersight:
    policies:
      power:
        - name: 5108
        - name: 9508
          power_allocation: 5600
        - name: server
          power_restore: LastState
      thermal:
        - name: 5108
          fan_control_mode: Balanced
        - name: 9508
          fan_control_mode: Balanced
